core-app:
  image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
  container_name: core-app
  ports:
    - "8000:80"

nginx:
  build: ./nginx
  container_name: core-app.local
  ports:
    - "80:80"
    - "443:443"
  links:
    - core-app