idp:
  build: ./src/IdentityServer
  container_name: idp
  ports: 
    - "8000:80"

api: 
  build: ./src/Api
  container_name: api
  ports: 
    - "8002:80"
  restart: on-failure

mvc:
  build: ./src/MvcClient
  container_name: mvc-client
  ports:
    - "8001:80"

  links:
    - idp
  
  restart: on-failure