idp:
  build: ./src/IdentityServer
  container_name: idp
  ports: 
    - "8000:80"

mvc:
  build: ./src/MvcClient
  container_name: mvc-client
  ports:
    - "8001:80"

  links:
    - idp
  
  restart: on-failure