idp:
  build: ./scr/IdentityServer
  container_name: idp
  ports: 
    - "8000:80"

mvc:
  build: ./scr/MvcClient
  container_name: mvc-client
  ports:
    - "8001:80"
    - "8002:443"
  links:
    - idp